# Generated by Django 3.2 on 2023-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del autor')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos del author')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.BooleanField(default=True, verbose_name='Author Activo/No Activo')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creción')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('status', models.BooleanField(default=True, verbose_name='Categoria Activada/No Activada')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
